[build-system]
requires = ["setuptools", "setuptools-rust", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "katcp-codec"
dynamic = ["version"]

[tool.setuptools.packages]
# Pure Python packages/modules
find = { where = ["python"] }

[tool.setuptools_scm]
# This section is needed to have setuptools_scm provide the version

[[tool.setuptools-rust.ext-modules]]
target = "katcp_codec._lib"
